service: aws-nodejs6 # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-3
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get