service: aws-csharp2

provider:
  name: aws
  runtime: dotnetcore2.1
  stage: dev
  region: eu-west-3
package:
  artifact: bin/release/netcoreapp2.1/publish/deploy-package.zip
functions:
  hello:
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::Hello
    events:
      - http:
          path: /
          method: get
