service: aws-go

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: eu-west-3
package:
 exclude:
   - ./**
 include:
   - ./bin/**
functions:
  hello:
    handler: bin/main
    events:
      - http:
          path: /
          method: get