service: aws-python # NOTE: update this with your service name

provider:
  name: aws
  runtime: python2.7
  stage: dev
  region: eu-west-3
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
